[package]
name = "delta-null-core-emulator-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
delta-null-core-emulator = { path = "../../lib/emulator" }
zmq = "0.10.0"
delta-null-core-emulator-protocol = { path = "../../lib/emulator-protocol" }
serde_json = "1.0.108"
serde = { version = "1.0.192", features = ["derive"] }
