[package]
name = "delta-null-core-assembler-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
clap-num = "1.0.2"
clap-stdin = "0.2.1"
delta-null-core-assembler = { path = "../../lib/assembler" }
delta-null-core-instructions = { path = "../../lib/instructions" }
serde_json = "1.0.108"
strum = { version = "0.25.0", features = ["derive"] }
