[package]
name = "delta-null-core-assembler-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
clap-stdin = "0.2.1"
delta-null-core-assembler = { path = "../../lib/assembler" }
