[package]
name = "delta-null-core-emulator-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
zmq = "0.10.0"
delta-null-core-emulator-protocol = { path = "../../lib/emulator-protocol" }
crossterm = "0.27.0"
ratatui = "0.24.0"
