[package]
name = "delta-null-lang-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
clap-stdin = "0.3.0"
delta-null-lang-backend = { path = "../../lib/backend" }
delta-null-lang-backend-core = { path = "../../lib/backend-core" }
delta-null-lang-frontend = { path = "../../lib/frontend" }
delta-null-core-instructions = { path = "../../../core/lib/instructions" }
